CREATE TABLE genai_prompt (
  id int IDENTITY(1,1) PRIMARY KEY,
  prompt NVARCHAR(MAX) NOT NULL DEFAULT '',
  created_by NVARCHAR(150) NOT NULL DEFAULT 'System',
  created_at DATETIMEOFFSET NOT NULL DEFAULT SYSDATETIMEOFFSET()
);